#!/usr/bin/env python3
"""Validate commit messages against the Conventional Commits format.

Intended to run as a pre-commit commit-msg hook.

NOTE: This script uses only the stdlib so it can run without uv/venv
in pre-commit hooks.

Usage:
    python scripts/check_commit_msg.py <commit-msg-file>
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

TYPES = {"feat", "fix", "refactor", "perf", "test", "docs", "build", "chore"}

# Scopes are the subsystems docs/SPEC.md names, plus the repo-level ones. Held
# as a literal set rather than derived from the spec's headings: a heading is
# prose that gets reworded, and a scope is a label that must stay stable across
# the history it groups. The list is CLOSED — an unknown scope is rejected, so
# add one here in the same commit that needs it.
SCOPES = {
    "protocol",  # §2  the wire format: frames, greeting, refusals
    "stream",  # §3  offsets, fan-out, the subscribe partition
    "subscriber",  # §4  the per-subscriber queue and its backpressure
    "server",  # §5  serve, routing
    "client",  # §5  connect, Subscription
    "log",  # §6  the litelink tier: columns, rows, replay
    "replay",  # §6  the resume path specifically
    "schema",  # JSON Schema <-> Arrow
    "cursor",  # where a consumer keeps its offset, local and remote
    "catchup",  # reading the gap from the archive
    "maintain",  # the maintainer subprocess
    "replicate",  # the litestream sidecar
    "errors",  # the refusal vocabulary and close codes
    "spec",  # docs/SPEC.md itself
    "ci",  # workflows, hooks, Justfile
    "deps",  # dependency floors and the lockfile
    "examples",  # the demo scripts
}

# Matches: type[(scope)][!]: description
SUBJECT_RE = re.compile(
    r"^(?P<type>[a-z]+)"
    r"(?:\((?P<scope>[a-z][a-z0-9-]*)\))?"
    r"(?P<breaking>!)?"
    r": "
    r"(?P<desc>.+)$"
)


def validate(message: str) -> list[str]:
    errors: list[str] = []

    # Comment lines are the template git appends to the editor buffer; they are
    # stripped before the message is stored, so validating them would reject
    # every interactive commit on the "# Please enter the commit message" line.
    body = "\n".join(
        line for line in message.splitlines() if not line.startswith("#")
    ).strip()

    lines = body.splitlines()
    if not lines:
        errors.append("Commit message is empty.")
        return errors

    subject = lines[0]

    # Merge and revert subjects are generated by git, not written by anyone.
    if subject.startswith(("Merge ", "Revert ", "fixup! ", "squash! ")):
        return errors

    match = SUBJECT_RE.match(subject)
    if not match:
        errors.append(
            f"Subject does not match conventional commits format.\n"
            f"  Expected: <type>(<scope>): <description>\n"
            f"  Got:      {subject}"
        )
        return errors

    commit_type = match.group("type")
    scope = match.group("scope")
    desc = match.group("desc")

    if commit_type not in TYPES:
        allowed = ", ".join(sorted(TYPES))
        errors.append(f"Unknown type '{commit_type}'. Allowed: {allowed}")

    if scope is not None and scope not in SCOPES:
        allowed = ", ".join(sorted(SCOPES))
        errors.append(f"Unknown scope '{scope}'. Allowed: {allowed}")

    if desc and desc[0].isupper():
        errors.append(f"Description must be lowercase: '{desc}'")

    if desc and desc.endswith("."):
        errors.append("Description must not end with a period.")

    if len(subject) > 72:
        errors.append(f"Subject line is {len(subject)} chars (max 72).")

    return errors


def main() -> None:
    if len(sys.argv) < 2:
        print("Usage: check_commit_msg.py <commit-msg-file>", file=sys.stderr)
        sys.exit(1)

    message = Path(sys.argv[1]).read_text()
    errors = validate(message)

    if errors:
        print("Commit message validation failed:\n", file=sys.stderr)
        for error in errors:
            print(f"  - {error}", file=sys.stderr)

        print(file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
